SOURCES_DIR=sources/
OBJECTS_DIR=objs/

FLAGS=-Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

all: SolverSquare

SolverSquare: $(OBJECTS_DIR)SolverSquare.o $(OBJECTS_DIR)Solve.o $(OBJECTS_DIR)Test.o
	g++ $(OBJECTS_DIR)SolverSquare.o $(OBJECTS_DIR)Solve.o $(OBJECTS_DIR)Test.o -o SolverSquare

$(OBJECTS_DIR)SolverSquare.o: $(SOURCES_DIR)SolverSquare.cpp $(SOURCES_DIR)Solve.h
	g++ $(FLAGS) -c $(SOURCES_DIR)SolverSquare.cpp -o $(OBJECTS_DIR)SolverSquare.o

$(OBJECTS_DIR)Solve.o: $(SOURCES_DIR)Solve.cpp $(SOURCES_DIR)Solve.h
	g++ $(FLAGS) -c $(SOURCES_DIR)Solve.cpp -o $(OBJECTS_DIR)Solve.o

$(OBJECTS_DIR)Test.o: $(SOURCES_DIR)Test.cpp $(SOURCES_DIR)Test.h
	g++ $(FLAGS) -c $(SOURCES_DIR)Test.cpp -o $(OBJECTS_DIR)Test.o
